name: kemo_client
description: A new Flutter project.
publish_to: 'none'
author: Diego Covarrubias <dcov@pm.me>

version: 0.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^1.4.1+1

  path_provider: ^1.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

